use crate::*;
use serde_json::json;
use std::collections::VecDeque;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Mutex;

mod test_check_support;
mod test_env;
mod test_git_support;

pub(crate) use test_check_support::*;
pub(crate) use test_env::*;
pub(crate) use test_git_support::*;

mod tests_app_server_protocol;
mod tests_check_command_args;
mod tests_check_config_validation;
mod tests_check_core;
mod tests_check_model_recovery;
mod tests_check_parser;
mod tests_check_query_output;
mod tests_check_response_repairs;
mod tests_check_restricted_scope;
mod tests_cli_aliases;
mod tests_config_env;
mod tests_evaluator_permissions;
mod tests_evaluator_prompt;
mod tests_gate;
mod tests_generator_config;
mod tests_git_runtime;
mod tests_history_cached_check;
mod tests_history_cooldown;
mod tests_history_exact_reuse;
mod tests_history_files;
mod tests_hook_install;
mod tests_init;
mod tests_logging_runtime;
mod tests_notes_crud;
mod tests_notes_index_behavior;
mod tests_scope_runtime;
mod tests_staged_preflight;
